### ISSUE TITLE
Version of bones in TileMill

### ISSUE THREAD

**Issue by RossGammon** [tilemill-project/tilemill#2260]
Hi,
I am writing on behalf of the Debian GIS team who would like to package Tile Mill for Debian. Currently, the version of node-bones in Debian is 2.0.1 (http://packages.qa.debian.org/n/node-bones.html). TillMill seems to need 1.3.27 which is actually newer than the version in Debian. With 2.0.1, this is the result:
anarcat@marcos:tilemill*$ sudo   su -s /bin/sh -c 'HOME=/usr/share/mapbox NODEPATH=/usr/lib/nodejs:/usr/share/tilemill /usr/bin/nodejs /usr/share/tilemill/index.js --config=/etc/tilemill/tilemill.config' mapbox
[tilemill] Note: Unknown option "server" in config file.
[tilemill] Note: Unknown option "server" in config file.
[tilemill] Plugin [carto] loaded.
[tilemill] Plugin [editor] loaded.
[tilemill] Plugin [fonts] loaded.
[tilemill] Plugin [templates] loaded.
[tilemill]
[tilemill] TypeError: Cannot call method 'error' of undefined
[tilemill]     at server.initialize (/usr/share/tilemill/servers/OAuth.bones:45:10)
[tilemill]     at Server (/usr/lib/nodejs/bones/server/server.js:10:10)
[tilemill]     at new child (/usr/share/javascript/backbone/backbone.js:1392:34)
[tilemill]     at servers.Core.initialize (/usr/share/tilemill/servers/Core.bones:16:14)
[tilemill]     at Server (/usr/lib/nodejs/bones/server/server.js:10:10)
[tilemill]     at new child (/usr/share/javascript/backbone/backbone.js:1392:34)
[tilemill]     at command.initialize (/usr/share/tilemill/commands/core.bones:224:28)
[tilemill]     at null.<anonymous> (/usr/lib/nodejs/bones/server/command.js:8:14)
[tilemill]     at command.bootstrap (/usr/share/tilemill/commands/core.bones:219:5)
[tilemill]     at Command (/usr/lib/nodejs/bones/server/command.js:7:10)
[tilemill] Error: child process: "core" failed with code "8"
[tilemill] Error: child process: "tile" failed with code "143"
[tilemill] Closing child process: core (pid:7988)
[tilemill] Closing child process: tile (pid:7990)
Exiting [tilemill]

Before we consider trying to package the 1.3.x series of node-bones instead, are there any plans to switch TIleMill to the 2.x.x series?

For information, the relevant Debian bug (against node-bones) is:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=743152

Regards,

Ross Gammon

**Comment by Komzpa** [comment]
@RossGammon hi!
is there any progress packaging Tilemill for Debian?

**Comment by RossGammon** [comment]
I wasn't able to get the last release working (dependency issues I think), and as the project had seemed to be stalled, I put my efforts elsewhere. But I will be happy to come back to it after a new release is made. There are a lot of Debian users & contributors that would like to see TIleMill in Debian!

**Comment by toton6868** [comment]
@Komzpa, @RossGammon and @springmeyer 

I (with the extensive help of my boss) have successfully installed Tilemill on Debian 9. We build it from source. We faced few problems when installing Mapnik. Few workaround in few files before Make help us a lot.  As we do not have GUI access to server we tried it as Service and make it available to remote users. We have changed the port and used 8000 and 8080 ports instead. So the Service started as

`./index.js --server=true --listenHost=0.0.0.0 --coreUrl=${TILEMILL_HOST}:8000 --tileUrl=${TILEMILL_HOST}:8080`

 But We are now facing few problem. Tilemill is opening but no default project is opening their layers. Then we have tested by opening new project and added a sample Shapefile. Its not opening and Saying 

`Unable to reach the local TileMill Server. Check the logs for details. If this problem persists please contact support at: http://support.mapbox.com/discussions/tilemill`

Any idea why it is happening?
