### ISSUE TITLE
Error: Cannot find module './srs_settings'

### ISSUE THREAD

**Issue by Rudloff** [tilemill-project/tilemill#2318]
Hello,

I have built tilemill from source on Debian but I get this error at launch:

```

> tilemill@0.10.1 start /home/pierre/tilemill
> ./index.js


/home/pierre/tilemill/node_modules/bones/server/plugin.js:108
        if (err.code !== 'ENOENT') throw err;
                                         ^
Error: Cannot find module './srs_settings'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pierre/tilemill/node_modules/millstone/node_modules/srs/lib/srs.js:11:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! tilemill@0.10.1 start: `./index.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the tilemill@0.10.1 start script.
npm ERR! This is most likely a problem with the tilemill package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls tilemill
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.2.0-4-amd64
npm ERR! command "node" "/usr/bin/npm" "start"
npm ERR! cwd /home/pierre/tilemill
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.10
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pierre/tilemill/npm-debug.log
npm ERR! not ok code 0
```

Regards,

**Comment by christianbundy** [comment]
For anyone in the future trying to figure out how to get Windshaft working after using <kbd>CTRL</kbd>+<kbd>C</kbd> during an `npm install`, this is it.
