### ISSUE TITLE
Error- encountered when trying this version on my Mac with 10.10.2 

### ISSUE THREAD

**Issue by darlacameron** [tilemill-project/tilemill#2495]
I encountered an error:
```
[tilemill] Error: listen EADDRINUSE
[tilemill]     at errnoException (net.js:904:11)
[tilemill]     at Server._listen2 (net.js:1042:14)
[tilemill]     at listen (net.js:1064:10)
[tilemill]     at Server.listen (net.js:1138:5)
[tilemill]     at server.start (/Applications/TileMill.app/Contents/Resources/app/servers/Tile.bones:18:14)
[tilemill]     at command.initialize (/Applications/TileMill.app/Contents/Resources/app/commands/tile.bones:24:26)
[tilemill]     at null.<anonymous> (/Applications/TileMill.app/Contents/Resources/app/node_modules/bones/server/command.js:8:14)
[tilemill]     at command.bootstrap (/Applications/TileMill.app/Contents/Resources/app/commands/tile.bones:18:5)
[tilemill]     at Command (/Applications/TileMill.app/Contents/Resources/app/node_modules/bones/server/command.js:7:10)
[tilemill]     at new child (/Applications/TileMill.app/Contents/Resources/app/node_modules/backbone/backbone.js:964:41)

```

**Comment by Komzpa** [comment]
sorry, not actionable without context. would you please try again with new tilemill from master and open another issue if problem persists?
