### ISSUE TITLE
Unable to launch tm on Ubuntu 14.04

### ISSUE THREAD

**Issue by flp-gpc** [tilemill-project/tilemill#2529]
I get this issue when I launch Tilemill in Ubuntu 14.04. It works fine on 12.04. Any idea ?

/home/map/tilemill/node_modules/tilelive/lib/statistics.js:24
    set remaining() {}, // read-only
                  ^
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/map/tilemill/node_modules/tilelive/lib/scheme.js:1:80)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by rodowi** [comment]
Duplicated: see #2511
