### ISSUE TITLE
install on debian

### ISSUE THREAD

**Issue by VonTalavang** [tilemill-project/tilemill#2583]
I have some issues here... using debian jessie

`ntala@ntala:~/Desktop/tileMill/tilemill$ sudo npm install
[sudo] password for ntala: 
npm WARN cannot run in wd tilemill@0.10.2 npm install npm (wd=/home/ntala/Desktop/tileMill/tilemill)
npm WARN package.json JSV@4.0.2 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
npm WARN package.json bones@1.3.30 No repository field.
npm WARN package.json modestmaps@3.3.5 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
npm WARN package.json backbone-dirty@1.1.3 No repository field.
npm WARN package.json jshint@0.2.3 No repository field.
\
> topcube@0.2.0 install /home/ntala/Desktop/tileMill/tilemill/node_modules/topcube
> node-gyp rebuild

Package gtk+-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtk+-2.0' found
gyp: Call to 'pkg-config gtk+-2.0 --cflags' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:344:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/ntala/Desktop/tileMill/tilemill/node_modules/topcube
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 

> mapnik@3.5.14 preinstall /home/ntala/Desktop/tileMill/tilemill/node_modules/mapnik
> npm install node-pre-gyp

/usr/bin/env: node: No such file or directory
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm WARN optional dep failed, continuing topcube@0.2.0
npm ERR! mapnik@3.5.14 preinstall: `npm install node-pre-gyp`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the mapnik@3.5.14 preinstall script.
npm ERR! This is most likely a problem with the mapnik package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install node-pre-gyp
npm ERR! You can get their info via:
npm ERR!     npm owner ls mapnik
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/ntala/Desktop/tileMill/tilemill
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
 
> sqlite3@3.1.8 install /home/ntala/Desktop/tileMill/tilemill/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

/usr/bin/env: node: No such file or directory
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
 
> zipfile@0.5.9 install /home/ntala/Desktop/tileMill/tilemill/node_modules/millstone/node_modules/zipfile
> node-pre-gyp install --fallback-to-build

/usr/bin/env: node: No such file or directory
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
|
> gdal@0.9.3 preinstall /home/ntala/Desktop/tileMill/tilemill/node_modules/millstone/node_modules/srs/node_modules/gdal
> npm install node-pre-gyp

/usr/bin/env: node: No such file or directory
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ntala/Desktop/tileMill/tilemill/npm-debug.log
npm ERR! not ok code 0
`

**Comment by tmcw** [comment]
TileMill expects you to have `node` installed and named `node`. You'll need to apt-get install `nodejs-legacy` in order to get your node called node.

**Comment by VonTalavang** [comment]
thanks for the quick answer.

I installed nodejs-legacy...
I installed 
```
npm install mapnik@3.x  (removed sudo... cause give me a error)
```
now:
```
$ ./index.js

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/ntala/Desktop/tileMill/tilemill/node_modules/mapnik/lib/binding/node-v11-linux-x64/mapnik.node)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ntala/Desktop/tileMill/tilemill/node_modules/mapnik/lib/mapnik.js:31:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```
i cant solve this
I already installed libstdc++6

any help ?

**Comment by VonTalavang** [comment]
Also i tried the other way in [https://tilemill-project.github.io/tilemill/docs/linux-install/](https://tilemill-project.github.io/tilemill/docs/linux-install/)

and: 
```
sudo apt-get install tilemill libmapnik nodejs
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package tilemill is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'tilemill' has no installation candidate
E: Unable to locate package libmapnik
```

so... is definitly not for Debian jessie ?

**Comment by tmcw** [comment]
Did you run the previous lines:

```
sudo add-apt-repository ppa:developmentseed/mapbox
sudo apt-get update
```

Before the apt-get install line? Please favor providing complete information so that we know whether this is a problem of missing a step or a problem with the actual install process.

**Comment by VonTalavang** [comment]
full log:

```
ntala@ntala:~/Desktop/tileMill/tilemill$ sudo add-apt-repository ppa:developmentseed/mapbox
[sudo] password for ntala: 
You are about to add the following PPA to your system:
 
 More info: https://launchpad.net/~developmentseed/+archive/ubuntu/mapbox
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keyring `/tmp/tmpfnmq2abi/secring.gpg' created
gpg: keyring `/tmp/tmpfnmq2abi/pubring.gpg' created
gpg: requesting key 0FB81AF3 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpfnmq2abi/trustdb.gpg: trustdb created
gpg: key 0FB81AF3: public key "Launchpad PPA for Development Seed" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
ntala@ntala:~/Desktop/tileMill/tilemill$ sudo apt-get update
Hit http://security.debian.org jessie/updates InRelease
Ign http://download.webmin.com sarge InRelease                                 
Ign http://ppa.launchpad.net jessie InRelease                                  
Ign http://httpredir.debian.org jessie InRelease                               
Ign http://download.bareos.org  InRelease                                      
Hit http://security.debian.org jessie/updates/non-free amd64 Packages          
Hit http://download.webmin.com sarge Release.gpg                               
Ign http://ppa.launchpad.net jessie InRelease                                  
Hit http://security.debian.org jessie/updates/non-free Translation-en          
Get:1 http://httpredir.debian.org jessie Release.gpg [2,373 B]                 
Hit http://security.debian.org jessie/updates/main amd64 Packages              
Hit http://download.bareos.org  Release.gpg                                    
Hit http://security.debian.org jessie/updates/contrib amd64 Packages           
Ign http://ppa.launchpad.net jessie InRelease                                  
Hit http://download.webmin.com sarge Release                                   
Get:2 http://httpredir.debian.org jessie Release [148 kB]                      
Hit http://security.debian.org jessie/updates/contrib Translation-en           
Hit http://security.debian.org jessie/updates/main Translation-en              
Hit http://ppa.launchpad.net trusty InRelease                                  
Hit http://download.bareos.org  Release                                        
Get:3 http://httpredir.debian.org jessie/main amd64 Packages [6,787 kB]        
Ign http://ppa.launchpad.net jessie Release.gpg                                
Ign http://ppa.launchpad.net jessie Release.gpg                                
Hit http://download.bareos.org  Packages                                       
Ign http://download.bareos.org  Translation-en_US                              
Ign http://download.bareos.org  Translation-en                                 
Ign http://ppa.launchpad.net jessie Release.gpg                                
Hit http://download.webmin.com sarge/contrib amd64 Packages                    
Ign http://ppa.launchpad.net jessie Release                                    
Ign http://ppa.launchpad.net jessie Release               
Ign http://ppa.launchpad.net jessie Release               
Hit http://ppa.launchpad.net trusty/main Sources            
Hit http://ppa.launchpad.net trusty/main amd64 Packages                        
Hit http://ppa.launchpad.net trusty/main Translation-en                        
Ign http://download.webmin.com sarge/contrib Translation-en_US                 
Ign http://download.webmin.com sarge/contrib Translation-en                    
Err http://ppa.launchpad.net jessie/main amd64 Packages                        
  404  Not Found
Ign http://ppa.launchpad.net jessie/main Translation-en_US                     
Ign http://ppa.launchpad.net jessie/main Translation-en                        
Err http://ppa.launchpad.net jessie/main amd64 Packages                        
  404  Not Found
Ign http://ppa.launchpad.net jessie/main Translation-en_US                     
Ign http://ppa.launchpad.net jessie/main Translation-en                        
Err http://ppa.launchpad.net jessie/main amd64 Packages                        
  404  Not Found
Get:4 http://httpredir.debian.org jessie/non-free amd64 Packages [83.6 kB]     
Ign http://ppa.launchpad.net jessie/main Translation-en_US                     
Get:5 http://httpredir.debian.org jessie/contrib amd64 Packages [50.2 kB]      
Ign http://ppa.launchpad.net jessie/main Translation-en                        
Hit http://httpredir.debian.org jessie/contrib Translation-en                  
Hit http://httpredir.debian.org jessie/main Translation-en                     
Hit http://httpredir.debian.org jessie/non-free Translation-en                 
Fetched 7,071 kB in 29s (237 kB/s)                                             
W: Failed to fetch http://ppa.launchpad.net/developmentseed/mapbox/ubuntu/dists/jessie/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/kakrueger/openstreetmap/ubuntu/dists/jessie/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu/dists/jessie/main/binary-amd64/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
ntala@ntala:~/Desktop/tileMill/tilemill$ sudo apt-get install tilemill libmapnik nodejs
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package tilemill is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'tilemill' has no installation candidate
E: Unable to locate package libmapnik
ntala@ntala:~/Desktop/tileMill/tilemill$ 
```

**Comment by Komzpa** [comment]
@VonTalavang there is no PPA for jessie.

There is packaging effort for Debian going there:
 https://github.com/tilemill-project/tilemill/issues/2260#issuecomment-256433757 - if you could get it running and write up in that thread, then it can be packaged for Debian natively.

**Comment by ssinger** [comment]
The 
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found

is because the binaries downloaded by npm for node_modules/mapnik are  not compatible with jessie.

To get around this I had to

1. Download and build and install newer mapnik than what comes with jessie, I used 3.0.12
2. under the tilemill directory I then did
cd node_modules/mapnik
npm install --build-from-source
(to get the above to use my newer mapnik I had to remove the libmapnik packages jessie installed)

I then did a npm install in the tilemill directory
After that I was able to start tilemill (latest from github) on jessie
