### ISSUE TITLE
Dockerfile for tilemill - running into setup problems

### ISSUE THREAD

**Issue by gitatr** [tilemill-project/tilemill#2595]
I am trying to create a Dockerfile to automatically install tilemill.

I have come this far:

```
FROM node:latest

RUN apt-get update && apt-get -y upgrade
RUN apt-get install git
RUN apt-get install -y nodejs-legacy
RUN npm install -g node-gyp
RUN git clone https://github.com/tilemill-project/tilemill.git
RUN cd /tilemill/ && node-gyp rebuild 
RUN cd tilemill && npm install

CMD /tilemill/index.js


```
This is where things go wrong:

```
Step 7/9 : RUN cd /tilemill/ && node-gyp rebuild
 ---> Running in ae9035bc7b8b
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@7.7.1 | linux | x64
gyp http GET https://nodejs.org/download/release/v7.7.1/node-v7.7.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v7.7.1/node-v7.7.1-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v7.7.1/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v7.7.1/SHASUMS256.txt
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/tilemill/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/7.7.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/7.7.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/tilemill',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /tilemill) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:308:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /tilemill
gyp ERR! node -v v7.7.1
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
The command '/bin/sh -c cd /tilemill/ && node-gyp rebuild' returned a non-zero code: 1

```

**Comment by darribas** [comment]
Did this work out? I'd be very interested on a container for TileMill!

**Comment by csytsma** [comment]
@darribas check out #2727, and related repo https://github.com/hmeine/tilemill_docker.
