### ISSUE TITLE
Error at installing

### ISSUE THREAD

**Issue by jmlipman** [tilemill-project/tilemill#2608]
After I installed tilemill using npm and I try to execute index.js I get the following error:

module.js:328
    throw err;
    ^

Error: Cannot find module '/sources/tilemill/node_modules/mapnik/lib/binding/node-v46-linux-x64/mapnik_settings.js'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/sources/tilemill/node_modules/mapnik/lib/mapnik.js:8:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)

This is what I get after I execute install npm
lipman@lipmanLenovo:/sources/tilemill$ npm install
loadDep:topcube → gunzTar ▌ ╢████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟

> topcube@0.2.0 install /sources/tilemill/node_modules/topcube
> node-gyp rebuild

make: Entering directory '/sources/tilemill/node_modules/topcube/build'
  CXX(target) Release/obj.target/topcube/src/topcube.o
  LINK(target) Release/topcube
  ACTION binding_gyp_action_after_build_target_move_topcube bin/topcube
  TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory '/sources/tilemill/node_modules/topcube/build'

> tilemill@0.10.2 preinstall /sources/tilemill
> npm install npm

npm WARN package.json JSV@4.0.2 'repositories' (plural) Not supported. Please pick one as the 'repository' field
npm WARN package.json backbone@0.3.3 No repository field.
npm WARN package.json backbone-dirty@1.1.3 No description
npm WARN package.json backbone-dirty@1.1.3 No repository field.
npm WARN package.json bcrypt-pbkdf@1.0.1 No repository field.
npm WARN package.json bones@1.3.30 No repository field.
npm WARN package.json buffer@4.9.1 buffer is also the name of a node core module.
npm WARN package.json dirty@0.9.9 No repository field.
npm WARN package.json events@1.1.1 events is also the name of a node core module.
npm WARN package.json jshint@0.2.3 No repository field.
npm WARN package.json mirror@0.3.3 No description
npm WARN package.json mirror@0.3.3 No repository field.
npm WARN package.json modestmaps@3.3.5 'repositories' (plural) Not supported. Please pick one as the 'repository' field
npm WARN package.json pause@0.0.1 No repository field.
npm WARN package.json punycode@1.3.2 punycode is also the name of a node core module.
npm WARN package.json querystring@0.2.0 querystring is also the name of a node core module.
npm WARN package.json string_decoder@0.10.31 string_decoder is also the name of a node core module.
npm WARN package.json tiletype@0.1.0 No repository field.
npm WARN package.json uid2@0.0.3 No repository field.
npm WARN package.json uglify-js@1.0.2 No description
npm WARN package.json url@0.10.3 url is also the name of a node core module.
npm@2.1.18 node_modules/npm

> tilemill@0.10.2 postinstall /sources/tilemill
> node ./lib/gitutil.js

tilemill@0.10.2 /sources/tilemill
├─┬ mapnik@3.5.14
│ └─┬ node-pre-gyp@0.6.38
│   └── npmlog@4.1.2 
├─┬ millstone@0.6.17
│ └─┬ srs@1.2.0
│   └─┬ gdal@0.9.6
│     └─┬ node-pre-gyp@0.6.36
│       └── npmlog@4.1.2 
├─┬ npm@2.1.18
│ └─┬ npm-registry-client@4.0.5
│   └── npmlog@4.1.2 
├─┬ sqlite3@3.1.13
│ └─┬ node-pre-gyp@0.6.38
│   └── npmlog@4.1.2 
└── topcube@0.2.0 

npm WARN tilemill@0.10.2 No license field.

I tried to use a different version of node (0.10.X) and I got different errors, so I'm a bit confused.

Thanks.

**Comment by almccon** [comment]
If we figure out what version of node we should use, we should include an .nvmrc file so we can use [nvm](https://github.com/creationix/nvm)

**Comment by IReese** [comment]
I'm using Ubuntu 16.04

I manged to get Tilemill up and running using the following:

```
git clone https://github.com/tilemill-project/tilemill.git
cd tilemill/
nvm use 4.9.1
npm install
```

**Comment by IReese** [comment]
Resolved.  At least on our end.

Under dependencies in the `package.json, I updated the mapnik version to instead use `"mapnik": "~3.7.2"` ' before I installed.

Then I installed Tilemill using `node4.9.1`

```
nvm use 4.9.1
npm install
```

Looks like this was in issue a while back in Mapnik:

mapnik/mapnik#3822
mapnik/mapnik#3872

but resolved in Mapnik v3.7.2
