### ISSUE TITLE
"Unhandled 'error' event" when running "index.js"

### ISSUE THREAD

**Issue by chrismp** [tilemill-project/tilemill#2617]
I ran `git clone` to download the tilemill repo to my home directory in Debian 9.3.

I went into the `tilemill/` directory and ran `./index.js`. Here's what the terminal outputted...

```
[tilemill] Started [Server Tile:20008].
[tilemill] Plugin [carto] loaded.
[tilemill] Plugin [editor] loaded.
[tilemill] Plugin [fonts] loaded.
[tilemill] Plugin [templates] loaded.
[tilemill] Started [Server Core:20009].
[tilemill] Client window created (pass --server=true to disable this)
[tilemill] Closing child process: core (pid:26811)
[tilemill] Closing child process: tile (pid:26817)
[tilemill] Closing child process: client (pid:undefined)
Exiting [tilemill]
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/chris/tilemill/node_modules/topcube/build/Release/topcube ENOENT
    at exports._errnoException (util.js:907:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:32)
    at onErrorNT (internal/child_process.js:363:16)
    at nextTickCallbackWith2Args (node.js:511:9)
    at process._tickDomainCallback (node.js:466:17)

```

I have v4.8.2. of `nodejs` and v1.4.21 of `npm`.

**Comment by chrismp** [comment]
Also, if I run `npm install` right now, I get this:

```
npm WARN package.json tilemill@0.10.2 No license field.

> tilemill@0.10.2 preinstall /home/chris/tilemill
> npm install npm

npm WARN package.json JSV@4.0.2 'repositories' (plural) Not supported. Please pick one as the 'repository' field
npm WARN package.json backbone-dirty@1.1.3 No description
npm WARN package.json backbone-dirty@1.1.3 No repository field.
npm WARN package.json bones@1.3.30 No repository field.
npm WARN package.json jshint@0.2.3 No repository field.
npm WARN package.json modestmaps@3.3.5 'repositories' (plural) Not supported. Please pick one as the 'repository' field
npm@2.1.18 node_modules/npm
npm WARN package.json JSV@4.0.2 'repositories' (plural) Not supported. Please pick one as the 'repository' field
npm WARN package.json JSV@4.0.2 No license field.
npm WARN package.json backbone-dirty@1.1.3 No description
npm WARN package.json backbone-dirty@1.1.3 No repository field.
npm WARN package.json backbone-dirty@1.1.3 No license field.
npm WARN package.json bones@1.3.30 No repository field.
npm WARN package.json bones@1.3.30 No license field.
npm WARN package.json chrono@1.0.5 No license field.
npm WARN package.json jshint@0.2.3 No repository field.
npm WARN package.json jshint@0.2.3 No license field.
npm WARN package.json mapbox-upload@4.2.4 No license field.
npm WARN package.json mbtiles@0.8.2 No license field.
npm WARN package.json millstone@0.6.17 No license field.
npm WARN package.json optimist@0.6.1 license should be a valid SPDX license expression
npm WARN package.json modestmaps@3.3.5 'repositories' (plural) Not supported. Please pick one as the 'repository' field
npm WARN package.json modestmaps@3.3.5 No license field.
npm WARN package.json passport-oauth@1.0.0 No license field.
npm WARN package.json semver@4.1.1 license should be a valid SPDX license expression
npm WARN package.json sax@0.6.1 license should be a valid SPDX license expression
npm WARN package.json sphericalmercator@1.0.5 No license field.
npm WARN package.json tilelive@5.12.3 No license field.
npm WARN package.json tilelive-mapnik@0.6.18 No license field.
npm WARN package.json underscore@1.6.0 No license field.
npm WARN package.json wax@6.4.2 No license field.
npm WARN engine topcube@0.2.0: wanted: {"node":">= 0.8.11 < 0.11.0"} (current: {"node":"4.8.2","npm":"1.4.21"})

> topcube@0.2.0 install /home/chris/tilemill/node_modules/topcube
> node-gyp rebuild

Package gtk+-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtk+-2.0' found
gyp: Call to 'pkg-config gtk+-2.0 --cflags' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:304:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Linux 4.9.0-4-amd64
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/chris/tilemill/node_modules/topcube
gyp ERR! node -v v4.8.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm WARN optional dep failed, continuing topcube@0.2.0

> tilemill@0.10.2 postinstall /home/chris/tilemill
> node ./lib/gitutil.js
```
