### ISSUE TITLE
Ubuntu 16 tilemill server no longer running / npm install fails

### ISSUE THREAD

**Issue by RobertSellers** [tilemill-project/tilemill#2630]
I have been running a stable tilemill server for some time now, only to have it crash out during some export tests while testing metatiles, and it no longer restarted. I was able to temporarily fix this by rebuilding the mapnik dependency by source, but now that no longer works either.  

So now I'm trying to just rebuild, but I'm running into some new npm / dependency issues that I'm not finding success figuring out.  I'm running

Ubuntu AWS 16.04
node- v 6.14.4
npm- v 3.10.10

```
gdal@0.9.8 install /mnt/tilemill/node_modules/gdal
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp ERR! UNCAUGHT EXCEPTION
node-pre-gyp ERR! stack TypeError: this is not a typed array.
node-pre-gyp ERR! stack     at Function.from (native)
node-pre-gyp ERR! stack     at Object.<anonymous> (/mnt/tilemill/node_modules/gdal/node_modules/node-pre-gyp/node_modules/tar/lib/parse.js:33:27)
node-pre-gyp ERR! stack     at Module._compile (module.js:410:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:417:10)
node-pre-gyp ERR! stack     at Module.load (module.js:344:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:301:12)
node-pre-gyp ERR! stack     at Module.require (module.js:354:17)
node-pre-gyp ERR! stack     at require (internal/module.js:12:17)
node-pre-gyp ERR! stack     at Object.<anonymous> (/mnt/tilemill/node_modules/gdal/node_modules/node-pre-gyp/node_modules/tar/lib/list.js:10:16)
node-pre-gyp ERR! stack     at Module._compile (module.js:410:26)
node-pre-gyp ERR! System Linux 4.4.0-1060-aws
node-pre-gyp ERR! command "/usr/bin/nodejs" "/mnt/tilemill/node_modules/gdal/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /mnt/tilemill/node_modules/gdal
node-pre-gyp ERR! node -v v4.2.6
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
tilemill@0.10.2 /mnt/tilemill
└── node-pre-gyp@0.11.0  extraneous

npm ERR! Linux 4.4.0-1060-aws
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! gdal@0.9.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the gdal@0.9.8 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gdal package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gdal
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls gdal
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/tilemill/npm-debug.log
```

**Comment by RobertSellers** [comment]
I'm not sure if this is a "solution", but the following tweak seems to have regained stability. I had been cloning with sudo and performing the npm install likewise. Simply granting full permission to the parent folder i.e.

```
sudo chown -R tilemill_user: /mnt/parent_dir
```

..worked. I also downgraded to node -v 4.9.1
