### ISSUE TITLE
Update Mocha Tests

### ISSUE THREAD

**Issue by csytsma** [tilemill-project/tilemill#2644]

**Comment by csytsma** [comment]
Current status of running tests:
===========

~/Development/tilemill/test $ npm test

tilemill@1.0.0 test /Users/csytsma/Development/tilemill
mocha --timeout 100000



Creating configuration dir /Users/csytsma/Development/tilemill/test/fixtures/files/.tilemill
Creating export dir /Users/csytsma/Development/tilemill/test/fixtures/files/export
Creating cache dir /Users/csytsma/Development/tilemill/test/fixtures/files/cache
Plugin [carto] loaded.
Plugin [editor] loaded.
Plugin [fonts] loaded.
Plugin [templates] loaded.
Started [Server Core:20009].
Started [Server Tile:20008].
  abilities
Note: Unknown option "host" in config file.
Plugin [carto] loaded.
Plugin [editor] loaded.
Plugin [fonts] loaded.
Plugin [templates] loaded.
Started [Server Core:20009].
Started [Server Tile:20008].
    1) GET should return JSON

  config
Note: Unknown option "host" in config file.
Plugin [carto] loaded.
Plugin [editor] loaded.
Plugin [fonts] loaded.
Plugin [templates] loaded.
Started [Server Core:20009].
Started [Server Tile:20008].
    ✓ GET should return JSON (120ms)
    ✓ PUT should update config
    ✓ GET should return updated config
    ✓ PUT should 409 on invalid config
    2) DELETE should 409

  datasource
    3) "before all" hook
    4) "after all" hook

  config loading pwnage
    5) there should only be one optimist module otherwise you are hosed
    6) there should only be one sqlite3 module otherwise you are hosed
    7) there should only be one mapnik module otherwise you are hosed

  export
Note: Unknown option "host" in config file.
Plugin [carto] loaded.
Plugin [editor] loaded.
Plugin [fonts] loaded.
Plugin [templates] loaded.
Started [Server Core:20009].
Started [Server Tile:20008].
    ✓ PUT should create export job (101ms)
    ✓ GET should retrieve export job
    8) DELETE should stop export job
    ✓ PUT create export job spanning the anti-meridian
[tilemill-ui] Exporting format: mbtiles
[tilemill-ui] Exporting format: mbtiles
[tilemill-ui] Error: ENOENT: no such file or directory, rename '/Users/csytsma/Development/tilemill/test/fixtures/files/cache/39906004-world_borders_merc/39906004-world_borders_merc.zip.download' -> '/Users/csytsma/Development/tilemill/test/fixtures/files/cache/39906004-world_borders_merc/39906004-world_borders_merc.zip'
[tilemill-ui] Exiting process [tm-demo_01.mbtiles]
[tilemill-ui] [tilemill] no crash logs found
Export process failed
[tilemill] no crash logs found
[tilemill-ui] Warning: using the name attribute for layers (like world here) is deprecated and will be removed in 1.0.0. Use id instead.
[tilemill-ui] Rendering export
[tilemill-ui] Persisting state in /Users/csytsma/Development/tilemill/test/fixtures/files/export/demo_anti-meridian.export every minute
[tilemill-ui] Persisting state in /Users/csytsma/Development/tilemill/test/fixtures/files/export/demo_anti-meridian.export every minute
[tilemill-ui] Completing export process
[tilemill-ui] Exiting process [tm-demo_anti-meridian.mbtiles]
{ progress: 1,
  status: 'complete',
  id: '15482092488781',
  format: 'mbtiles',
  project: 'demo_01',
  tile_format: 'png',
  filename: 'demo_anti-meridian.mbtiles',
  bbox: [ 175, 31.8402, -175, 71.9245 ],
  minzoom: 0,
  maxzoom: 2,
  pid: 24165,
  created: 1548209259250,
  remaining: 0,
  updated: 1548209263948,
  rate: 13 }
    ✓ GET anti-meridian job to see if it succeeded (5061ms)
    9) DELETE should remove anti-meridian export job
    10) GET should find no export jobs

  project
Note: Unknown option "host" in config file.
Plugin [carto] loaded.
Plugin [editor] loaded.
Plugin [fonts] loaded.
Plugin [templates] loaded.
Started [Server Core:20009].
Started [Server Tile:20008].
    ✓ collection should list projects
    ✓ model should load JSON
    ✓ model should not have an update
    ✓ model should have an update
Warning: using the name attribute for layers (like world here) is deprecated and will be removed in 1.0.0. Use id instead.
    ✓ PUT should create a project (76ms)
    ✓ GET should load created project
    11) DELETE should remove project
    ✓ PUT should fail with invalid id
Warning: using the name attribute for layers (like world here) is deprecated and will be removed in 1.0.0. Use id instead.
Warning: using the name attribute for layers (like world here) is deprecated and will be removed in 1.0.0. Use id instead.
    ✓ PUT should fail with invalid stylesheet

  tile endpoint
Note: Unknown option "host" in config file.
Plugin [carto] loaded.
Plugin [editor] loaded.
Plugin [fonts] loaded.
Plugin [templates] loaded.
Started [Server Core:20009].
Started [Server Tile:20008].
    ✓ should 404 for missing project
Warning: using the name attribute for layers (like world here) is deprecated and will be removed in 1.0.0. Use id instead.
    ✓ should 200 (tile) for existing project (142ms)
    ✓ should 200 (grid) for existing project (115ms)


  19 passing (16s)
  11 failing

  1) abilities
       GET should return JSON:

      Uncaught AssertionError [ERR_ASSERTION]: v0.11-deprecated-4-g5c757115
      + expected - actual

      -false
      +true

      at /Users/csytsma/Development/tilemill/test/abilities.test.js:31:24
      at IncomingMessage.<anonymous> (test/support/start.js:165:13)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:139:11)
      at process._tickCallback (internal/process/next_tick.js:181:9)

  2) config
       DELETE should 409:
     Uncaught Error: socket hang up
      at createHangUpError (_http_client.js:342:15)
      at Socket.socketOnEnd (_http_client.js:437:23)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:139:11)
      at process._tickCallback (internal/process/next_tick.js:181:9)

  3) datasource
       "before all" hook:
     Uncaught Error: Command failed:         psql -d postgres -c "DROP DATABASE IF EXISTS tilemill_test;" ;         createdb -E UTF8 -T template_postgis tilemill_test ;          psql -d tilemill_test -f /Users/csytsma/Development/tilemill/test/fixtures/tilemill_test.sql
NOTICE:  database "tilemill_test" does not exist, skipping
createdb: database creation failed: ERROR:  template database "template_postgis" does not exist
psql: FATAL:  database "tilemill_test" does not exist

      at ChildProcess.exithandler (child_process.js:281:12)
      at maybeClose (internal/child_process.js:915:16)
      at Socket.stream.socket.on (internal/child_process.js:336:11)
      at Pipe._handle.close [as _onclose] (net.js:561:12)

  4) datasource
       "after all" hook:
     TypeError: Cannot read property 'close' of undefined
      at Context.<anonymous> (test/datasource.test.js:24:10)

  5) config loading pwnage
       there should only be one optimist module otherwise you are hosed:

      Uncaught AssertionError [ERR_ASSERTION]: you have more than one copy of optimist (`npm ls optimist`)
      + expected - actual

      -4
      +1

      at /Users/csytsma/Development/tilemill/test/duplicate_module.test.js:24:20
      at /Users/csytsma/Development/tilemill/test/duplicate_module.test.js:13:20
      at ChildProcess.exithandler (child_process.js:273:7)
      at maybeClose (internal/child_process.js:915:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

  6) config loading pwnage
       there should only be one sqlite3 module otherwise you are hosed:

      Uncaught AssertionError [ERR_ASSERTION]: you have more than one copy of sqlite3 (`npm ls sqlite3`)
      + expected - actual

      -3
      +1

      at /Users/csytsma/Development/tilemill/test/duplicate_module.test.js:24:20
      at /Users/csytsma/Development/tilemill/test/duplicate_module.test.js:13:20
      at ChildProcess.exithandler (child_process.js:273:7)
      at maybeClose (internal/child_process.js:915:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

  7) config loading pwnage
       there should only be one mapnik module otherwise you are hosed:

      Uncaught AssertionError [ERR_ASSERTION]: you have more than one copy of mapnik (`npm ls mapnik`)
      + expected - actual

      -3
      +1

      at /Users/csytsma/Development/tilemill/test/duplicate_module.test.js:24:20
      at /Users/csytsma/Development/tilemill/test/duplicate_module.test.js:13:20
      at ChildProcess.exithandler (child_process.js:273:7)
      at maybeClose (internal/child_process.js:915:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

  8) export
       DELETE should stop export job:
     Uncaught Error: socket hang up
      at createHangUpError (_http_client.js:342:15)
      at Socket.socketOnEnd (_http_client.js:437:23)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:139:11)
      at process._tickCallback (internal/process/next_tick.js:181:9)

  9) export
       DELETE should remove anti-meridian export job:
     Uncaught Error: socket hang up
      at createHangUpError (_http_client.js:342:15)
      at Socket.socketOnEnd (_http_client.js:437:23)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:139:11)
      at process._tickCallback (internal/process/next_tick.js:181:9)

  10) export
       GET should find no export jobs:

      Uncaught AssertionError [ERR_ASSERTION]: [] deepEqual [ { progress: 0,
    status: 'error',
    id: '1548209248878',
    format: 'mbtiles',
    project: 'demo_01',
    tile_format: '
      + expected - actual

      -[]
      +[
      +  {
      +    "bbox": [
      +      -29.5642
      +      31.8402
      +      42.1545
      +      71.9245
      +    ]
      +    "created": 1548209259156
      +    "error": "Error: ENOENT: no such file or directory, rename &#x27;/Users/csytsma/Development/tilemill/test/fixtures/files/cache/39906004-world_borders_merc/39906004-world_borders_merc.zip.download&#x27; -&gt; &#x27;/Users/csytsma/Development/tilemill/test/fixtures/files/cache/39906004-world_borders_merc/39906004-world_borders_merc.zip&#x27;"
      +    "filename": "demo_01.mbtiles"
      +    "format": "mbtiles"
      +    "id": "1548209248878"
      +    "maxzoom": 2
      +    "minzoom": 0
      +    "pid": 24164
      +    "progress": 0
      +    "project": "demo_01"
      +    "status": "error"
      +    "tile_format": "png"
      +    "updated": 1548209262633
      +  }
      +  {
      +    "bbox": [
      +      175
      +      31.8402
      +      -175
      +      71.9245
      +    ]
      +    "created": 1548209259250
      +    "filename": "demo_anti-meridian.mbtiles"
      +    "format": "mbtiles"
      +    "id": "15482092488781"
      +    "maxzoom": 2
      +    "minzoom": 0
      +    "pid": 24165
      +    "progress": 1
      +    "project": "demo_01"
      +    "rate": 13
      +    "remaining": 0
      +    "status": "complete"
      +    "tile_format": "png"
      +    "updated": 1548209263948
      +  }
      +]

      at /Users/csytsma/Development/tilemill/test/export.test.js:162:16
      at IncomingMessage.<anonymous> (test/support/start.js:165:13)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:139:11)
      at process._tickCallback (internal/process/next_tick.js:181:9)

  11) project
       DELETE should remove project:
     Uncaught Error: socket hang up
      at createHangUpError (_http_client.js:342:15)
      at Socket.socketOnEnd (_http_client.js:437:23)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:139:11)
      at process._tickCallback (internal/process/next_tick.js:181:9)

npm ERR! Test failed.  See above for more details.
