### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by sommerluk** [tilemill-project/tilemill#2698]
**Describe the bug**
Tilemill crashs:
```
This script will run the TileMill server. You will need to leave this server running while you are using TileMill. When you are finished using TileMill you can shutdown the server by holding the control key while hitting the c key. Or, you can close the Terminal window.                                                                                                                
----------------------------------------------------------------------


> tilemill@1.0.1 start /home/sommerluk/Dokumente/OSM/tilemill
> ./index.js

[tilemill] Starting in server mode.
[tilemill] url.js:337
[tilemill]       this.hostname = toASCII(this.hostname, true);
[tilemill]                       ^
[tilemill] 
[tilemill] Error: Cannot convert name to ASCII
[tilemill]     at Url.parse (url.js:337:23)
[tilemill]     at Object.urlParse [as parse] (url.js:97:13)
[tilemill]     at Object.validate_config (/home/sommerluk/Dokumente/OSM/tilemill/node_modules/mapnik/node_modules/node-pre-gyp/lib/util/versioning.js:223:28)
[tilemill]     at Object.exports.find (/home/sommerluk/Dokumente/OSM/tilemill/node_modules/mapnik/node_modules/node-pre-gyp/lib/pre-binding.js:20:15)
[tilemill]     at Object.<anonymous> (/home/sommerluk/Dokumente/OSM/tilemill/node_modules/mapnik/lib/mapnik.js:6:27)
[tilemill]     at Module._compile (module.js:653:30)
[tilemill]     at Object.Module._extensions..js (module.js:664:10)
[tilemill]     at Module.load (module.js:566:32)
[tilemill]     at tryModuleLoad (module.js:506:12)
[tilemill]     at Function.Module._load (module.js:498:3)
[tilemill] Error: child process: "core" failed with code "1"
[tilemill] Error: child process: "tile" failed with signal "SIGTERM"
[tilemill] Closing child process: core (pid:12970)
[tilemill] Closing child process: tile (pid:12971)
Exiting [tilemill]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tilemill@1.0.1 start: `./index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tilemill@1.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sommerluk/.npm/_logs/2019-03-17T21_14_11_176Z-debug.log

```

**Environment: (Note: We are not setup to test on Linux or Windows so help may be slower on those OSs)**
 - openSUSE 15.0
 - `node -v` v8.15.0

**To Reproduce**
1. `git clone` this repository
2. `cd tilemill`
2. `npm install`
3. `./tilemill.sh` (I've removed previously in this script the line starting with `source` because I do not have `${HOME}/.bash_profile`)

**Expected behavior**
Tilemill runs without crashing.

**Installation Method**
See “Steps to reproduce”

**Screenshots and logfile**
The logfile:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node8', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.9.0
3 info using node@v8.15.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle tilemill@1.0.1~prestart: tilemill@1.0.1
6 info lifecycle tilemill@1.0.1~start: tilemill@1.0.1
7 verbose lifecycle tilemill@1.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle tilemill@1.0.1~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/sommerluk/Dokumente/OSM/tilemill/node_modules/.bin:/home/sommerluk/bin:/usr/local/bin:/usr/bin:/bin:/usr/lib/mit/sbin
9 verbose lifecycle tilemill@1.0.1~start: CWD: /home/sommerluk/Dokumente/OSM/tilemill
10 silly lifecycle tilemill@1.0.1~start: Args: [ '-c', './index.js' ]
11 silly lifecycle tilemill@1.0.1~start: Returned: code: 1  signal: null
12 info lifecycle tilemill@1.0.1~start: Failed to exec start script
13 verbose stack Error: tilemill@1.0.1 start: `./index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid tilemill@1.0.1
15 verbose cwd /home/sommerluk/Dokumente/OSM/tilemill
16 verbose Linux 4.12.14-lp150.11-default
17 verbose argv "/usr/bin/node8" "/usr/local/bin/npm" "start"
18 verbose node v8.15.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error tilemill@1.0.1 start: `./index.js`
22 error Exit status 1
23 error Failed at the tilemill@1.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Additional context**
None.

**Comment by csytsma** [comment]
@sommerluk did you have any luck figuring this out? We don't have an openSUSE box to easily test on. Does your computer's hostname have any non-standard characters?
What does `hostname -f` or `hostname -h` return when typed on the command line?

**Comment by sommerluk** [comment]
I do not longer have this setup available.

Should I close this issue?

**Comment by AlexKraak** [comment]
Hi im getting this same error on opensuse tumbleweed
the output of hostname is 'booter' but hostname -f returns 'name or service not known'
