### ISSUE TITLE
install issue stemver

### ISSUE THREAD

**Issue by zacchaeusliang** [tilemill-project/tilemill#2757]
**Describe the bug**

install error when running npm install 

Enviorment

**To Reproduce**
1. clone repo 
2. run npm install 

**Screenshots and logfile**
If applicable, add screenshots or a copy of your terminal output to help explain your problem.
```

2324 verbose stack TypeError: Invalid Version: 2.0.0alpha1
2324 verbose stack     at new SemVer (/usr/share/nodejs/semver/classes/semver.js:38:13)
2324 verbose stack     at compareBuild (/usr/share/nodejs/semver/functions/compare-build.js:3:20)
2324 verbose stack     at /usr/share/nodejs/semver/functions/sort.js:2:51
2324 verbose stack     at Array.sort (<anonymous>)
2324 verbose stack     at Object.sort (/usr/share/nodejs/semver/functions/sort.js:2:36)
2324 verbose stack     at Advisory.[calculateRange] (/usr/share/nodejs/@npmcli/metavuln-calculator/lib/advisory.js:159:28)
2324 verbose stack     at Advisory.load (/usr/share/nodejs/@npmcli/metavuln-calculator/lib/advisory.js:148:28)
2324 verbose stack     at Calculator.[calculate] (/usr/share/nodejs/@npmcli/metavuln-calculator/lib/index.js:59:14)
2324 verbose stack     at async Promise.all (index 0)
2324 verbose stack     at async Map.[init] (/usr/share/nodejs/@npmcli/arborist/lib/audit-report.js:192:7)
2325 verbose cwd /home/zack/tilemill
2326 verbose Linux 5.15.0-40-generic
2327 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
2328 verbose node v12.22.9
2329 verbose npm  v8.5.1
2330 error Invalid Version: 2.0.0alpha1
2331 verbose exit 1
2332 timing npm Completed in 169875ms
2333 verbose unfinished npm timer command:install 1656178448133
2334 verbose unfinished npm timer reify 1656178448135
2335 verbose unfinished npm timer reify:audit 1656178595884
2336 verbose unfinished npm timer reify:unpack 1656178595891
2337 verbose unfinished npm timer reifyNode:node_modules/wax 1656178595918
2338 verbose unfinished npm timer reifyNode:node_modules/tilelive 1656178595918
2339 verbose unfinished npm timer reifyNode:node_modules/millstone 1656178595920
2340 verbose unfinished npm timer auditReport:init 1656178597881
2341 verbose unfinished npm timer metavuln:calculate:security-advisory:bones:9Lqcafwr8MCGsZVZSd2Z/kJ/cba0KLkz/0y9IrvG7b+7thu8tGXmi0PYv7SFoAgQOHveA+RWst8n3uRFNAquug== 1656178617381
2342 verbose unfinished npm timer metavuln:load:security-advisory:bones:9Lqcafwr8MCGsZVZSd2Z/kJ/cba0KLkz/0y9IrvG7b+7thu8tGXmi0PYv7SFoAgQOHveA+RWst8n3uRFNAquug== 1656178617804
2343 verbose code 1
2344 error A complete log of this run can be found in:
2344 error     /home/zack/.npm/_logs/2022-06-25T17_34_07_946Z-debug-0.log
zack@zack-Standard-PC-Q35-ICH9-2009:~/tilemill$ rm node_modules/
.
```

**Comment by csytsma** [comment]
Looks like you're using Node v12.22.9, you need to be on Lts/Carbon:
- Ubuntu: v8.11.x
- OSX: v8.15.x lts/carbon

**Comment by zacchaeusliang** [comment]
I got it to  run using docker is there a way to use osm bright with the docker image?

**Comment by csytsma** [comment]
The OSM Bright is really just a sample project, with some initial data loaded in Postgres.

Follow the OSM Bright for MacOS: https://tilemill-project.github.io/tilemill/docs/guides/osm-bright-mac-quickstart/

There are probably newer ways to install the required tools, so follow latest standards (Postgres, postgis, GDAL, osm2pgsql)

Import OSM data

Download and unzip OSMbright project.

If you are successful, would be great if you can take notes and could either create or update the online guide.
